### ISSUE TITLE
May I know who you are? 

### ISSUE THREAD

**Issue by bhavya32** [GodCode/glowing-octo-succotash#3]
@GodCode I am surprised you joined a week ago and  followed me? I am not an owner of any repo, nor am contributor. How did you got my link? And @Manjit2003, you were present in issues in Baileys I remember. Not any issue but little surprised.

**Comment by GodCode** [comment]
@bhavya32   

**No Worries...** 

Thats just my another account for hacktoberfest... I followed because you seem to me like an Indian and we both have same intrests i.e WhatsApp rev-eng. If you want I can unfollow...

**Comment by bhavya32** [comment]
@GodCode No need to unfollow. I was just curious :)

**Comment by GodCode** [comment]
Are you an Indian?? If you want you can use this repo for hacktoberfest... I will accept the PR's
